# Generated by Django 5.0.2 on 2024-02-20 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                ("f_id", models.AutoField(primary_key=True, serialize=False)),
                ("item", models.CharField(max_length=255)),
                ("veg_or_non_veg", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                ("userid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("rating", models.DecimalField(decimal_places=1, max_digits=2)),
                ("rating_count", models.IntegerField()),
                ("cost", models.CharField(max_length=255)),
                ("cuisine", models.CharField(max_length=255)),
                ("lic_no", models.CharField(max_length=255)),
                ("link", models.URLField()),
                ("address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("marital_status", models.CharField(max_length=255)),
                ("occupation", models.CharField(max_length=255)),
                (
                    "monthly_income",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("educational_qualifications", models.TextField()),
                ("family_size", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                ("menu_id", models.AutoField(primary_key=True, serialize=False)),
                ("cuisine", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Restaurent_Server.food",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Restaurent_Server.restaurant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateTimeField()),
                ("sales_qty", models.IntegerField()),
                ("sales_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=10)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Restaurent_Server.restaurant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Restaurent_Server.user",
                    ),
                ),
            ],
        ),
    ]
