# Generated by Django 5.0.2 on 2024-02-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Restaurent_Server", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="rating",
            field=models.CharField(max_length=255),
        ),
    ]
