# Generated by Django 5.0.2 on 2024-02-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Restaurent_Server", "0002_alter_restaurant_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="rating",
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="rating_count",
            field=models.CharField(max_length=255),
        ),
    ]
