# Generated by Django 5.0.2 on 2024-02-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Restaurent_Server", "0003_alter_restaurant_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="rating",
            field=models.CharField(max_length=255),
        ),
    ]
