# Generated by Django 5.0.2 on 2024-02-20 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Restaurent_Server", "0004_alter_restaurant_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurant",
            old_name="userid",
            new_name="id",
        ),
    ]
