# Generated by Django 5.0.2 on 2024-02-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Restaurent_Server", "0005_rename_userid_restaurant_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="monthly_income",
            field=models.CharField(max_length=255),
        ),
    ]
