# Generated by Django 5.0.2 on 2024-02-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Restaurent_Server", "0006_alter_user_monthly_income"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
